// ---------------------------------------------------------------------------
// assistant-exports.test.mjs — unit tests for the export primitives in
// src/api/lib/assistant-exports.ts (pure, no DB / no Supabase).
//
// Covers:
//   - CSV escaping (comma, quote, CR/LF in cells; nulls; mixed types)
//   - CSV header inference from union of row keys
//   - Excel buffer validates as a ZIP (xlsx is a zip; first 2 bytes "PK")
//   - PDF generation produces a valid PDF (starts with "%PDF")
//   - sanitiseFilename strips path traversal and unsafe chars
//   - filename gets the right extension forced on
// ---------------------------------------------------------------------------
import test from 'node:test';
import assert from 'node:assert/strict';
import { register } from 'node:module';
import { pathToFileURL } from 'node:url';

let loaderRegistered = false;
try {
  register('tsx/esm', pathToFileURL('./'));
  loaderRegistered = true;
} catch {
  // Native type-stripping handles it.
}

const mod = await import('../src/api/lib/assistant-exports.ts');
const {
  csvEscapeCell,
  buildCsv,
  buildExcelWorkbook,
  buildSimpleTablePdf,
  sanitiseFilename,
} = mod;

test('csv module loaded', () => {
  assert.equal(typeof csvEscapeCell, 'function');
  assert.equal(typeof buildCsv, 'function');
  assert.equal(typeof buildExcelWorkbook, 'function');
  assert.equal(typeof buildSimpleTablePdf, 'function');
  assert.equal(typeof sanitiseFilename, 'function');
});

test('csv escapes commas with double-quote wrapping', () => {
  assert.equal(csvEscapeCell('hello, world'), '"hello, world"');
});

test('csv escapes embedded double-quotes by doubling', () => {
  assert.equal(csvEscapeCell('she said "hi"'), '"she said ""hi"""');
});

test('csv wraps cells with newlines or CR', () => {
  assert.equal(csvEscapeCell('line1\nline2'), '"line1\nline2"');
  assert.equal(csvEscapeCell('cr\rhere'), '"cr\rhere"');
  assert.equal(csvEscapeCell('crlf\r\nboth'), '"crlf\r\nboth"');
});

test('csv leaves plain strings alone', () => {
  assert.equal(csvEscapeCell('plain text'), 'plain text');
  assert.equal(csvEscapeCell('123-abc_xyz'), '123-abc_xyz');
});

test('csv handles numbers, booleans, nulls', () => {
  assert.equal(csvEscapeCell(42), '42');
  assert.equal(csvEscapeCell(0), '0');
  assert.equal(csvEscapeCell(true), 'true');
  assert.equal(csvEscapeCell(false), 'false');
  assert.equal(csvEscapeCell(null), '');
  assert.equal(csvEscapeCell(undefined), '');
});

test('buildCsv assembles header + rows with CRLF', () => {
  const csv = buildCsv([
    { id: 1, name: 'Alice', note: 'hello' },
    { id: 2, name: 'Bob', note: 'with, comma' },
  ]);
  const lines = csv.split('\r\n').filter((s) => s.length > 0);
  assert.equal(lines.length, 3);
  assert.equal(lines[0], 'id,name,note');
  assert.equal(lines[1], '1,Alice,hello');
  assert.equal(lines[2], '2,Bob,"with, comma"');
});

test('buildCsv unions keys across rows (handles missing fields)', () => {
  const csv = buildCsv([
    { a: 1, b: 2 },
    { a: 3, c: 4 },
  ]);
  const headerLine = csv.split('\r\n')[0];
  // Header order = first-seen across all rows: a, b, c
  assert.equal(headerLine, 'a,b,c');
  const dataLines = csv.split('\r\n').slice(1).filter((l) => l.length > 0);
  assert.equal(dataLines[0], '1,2,');
  assert.equal(dataLines[1], '3,,4');
});

test('buildCsv on empty rows returns empty string', () => {
  assert.equal(buildCsv([]), '');
});

test('buildExcelWorkbook produces a ZIP-shaped buffer', () => {
  const buf = buildExcelWorkbook([
    { name: 'Sheet1', rows: [{ a: 1, b: 'x' }, { a: 2, b: 'y' }] },
  ]);
  assert.ok(buf instanceof Uint8Array, 'should be Uint8Array');
  assert.ok(buf.byteLength > 0, 'should have bytes');
  // xlsx is a ZIP archive → starts with "PK\x03\x04".
  assert.equal(buf[0], 0x50);
  assert.equal(buf[1], 0x4b);
});

test('buildExcelWorkbook with multiple sheets', () => {
  const buf = buildExcelWorkbook([
    { name: 'A', rows: [{ x: 1 }] },
    { name: 'B', rows: [{ y: 2 }] },
  ]);
  assert.ok(buf.byteLength > 0);
  assert.equal(buf[0], 0x50);
  assert.equal(buf[1], 0x4b);
});

test('buildExcelWorkbook with empty sheets still produces a valid file', () => {
  const buf = buildExcelWorkbook([{ name: 'Empty', rows: [] }]);
  assert.ok(buf.byteLength > 0);
  assert.equal(buf[0], 0x50);
  assert.equal(buf[1], 0x4b);
});

test('buildSimpleTablePdf produces a valid PDF', async () => {
  const buf = await buildSimpleTablePdf({
    title: 'Test Report',
    subtitle: '2026-05-30',
    columns: ['SO', 'Customer', 'Amount'],
    rows: [
      ['SO-2605-001', 'Houzs Century', '1,234.00'],
      ['SO-2605-002', 'Carress', '987.50'],
    ],
    totals: ['Total', '2 orders', '2,221.50'],
    footer: 'Generated by Hookka AI',
  });
  assert.ok(buf instanceof Uint8Array, 'should be Uint8Array');
  assert.ok(buf.byteLength > 100, 'PDF should be > 100 bytes');
  // PDF files start with "%PDF-".
  const head = new TextDecoder().decode(buf.slice(0, 5));
  assert.equal(head, '%PDF-');
});

test('buildSimpleTablePdf does not throw on long text that needs clipping', async () => {
  const longText = 'x'.repeat(200);
  const buf = await buildSimpleTablePdf({
    title: 'Stress',
    columns: ['Long'],
    rows: [[longText], [longText]],
  });
  assert.ok(buf.byteLength > 0);
});

test('buildSimpleTablePdf paginates when rows exceed page', async () => {
  const rows = Array.from({ length: 100 }, (_, i) => [`row ${i}`, `value ${i}`]);
  const buf = await buildSimpleTablePdf({
    title: 'Paginate test',
    columns: ['A', 'B'],
    rows,
  });
  assert.ok(buf.byteLength > 0);
  // A multi-page PDF should clearly be larger than ~2 KB.
  assert.ok(buf.byteLength > 2000);
});

test('sanitiseFilename strips path traversal', () => {
  assert.equal(
    sanitiseFilename('../../etc/passwd', '.csv'),
    'etc-passwd.csv',
  );
  assert.equal(sanitiseFilename('/abs/path/file', '.csv'), 'abs-path-file.csv');
  assert.equal(
    sanitiseFilename('..\\..\\windows\\file', '.csv'),
    'windows-file.csv',
  );
});

test('sanitiseFilename forces extension', () => {
  assert.equal(sanitiseFilename('myfile', '.xlsx'), 'myfile.xlsx');
  assert.equal(sanitiseFilename('myfile.txt', '.xlsx'), 'myfile.xlsx');
  assert.equal(sanitiseFilename('myfile.xlsx', '.xlsx'), 'myfile.xlsx');
});

test('sanitiseFilename strips weird chars', () => {
  // The dollar sign is not in the safe list, gets replaced with -.
  assert.equal(
    sanitiseFilename('weird $@!file', '.csv'),
    'weird-file.csv',
  );
});

test('sanitiseFilename falls back when name is empty', () => {
  const r = sanitiseFilename('', '.csv');
  assert.match(r, /^export-\d+\.csv$/);
});

void loaderRegistered;
