-- ---------------------------------------------------------------------------
-- 0109_so_item_custom_specials.sql
--
-- Free-text custom special orders on sales_order_items.
--
-- Operator can attach 0..N "Other (custom)" specials to a SO line, each with
-- its own description + surcharge. Lets the shop floor cover edge cases
-- (e.g. "Custom Foam Density 35D", "Special leg ferrules") without bloating
-- the master Specials maintenance config beyond 100 entries.
--
-- Stored as JSON array because the count and shape varies per line:
--   [
--     { "description": "Custom Foam Density 35D", "surchargeSen": 5000 },
--     { "description": "Special ferrules",        "surchargeSen": 2000 }
--   ]
--
-- The aggregate surcharge from this column is folded into the existing
-- special_order_price_sen at write time (computed client-side, mirrored on
-- the server). The existing `special_order` text column also receives a
-- joined "OTHER: <desc>" suffix so legacy readers (DO print, invoice,
-- detail page) continue to render the full list without code changes.
--
-- camelCase identifier `customSpecials` is already mapped to `custom_specials`
-- in src/api/lib/column-rename-map.json (line 137) so route SQL keeps using
-- the camelCase form via the d1-compat adapter.
--
-- History: this column was originally authored as
-- migrations/0074_so_item_custom_specials.sql (legacy SQLite source) but the
-- corresponding migrations-postgres/ file was never generated, so the column
-- never landed in Supabase. The legacy 0074 file has been removed in this
-- commit; this file is the canonical migration.
-- ---------------------------------------------------------------------------
ALTER TABLE sales_order_items
  ADD COLUMN IF NOT EXISTS custom_specials TEXT;
