-- 0142_organisations_registry.sql
-- Convert the hardcoded HOOKKA + OHANA org list into a CRUD-able registry of
-- sister companies. Supplier rows pick which org's letterhead prints on
-- their PO. The legal/AP buyer is always HOOKKA — this is purely a
-- frontend letterhead override. See src/lib/generate-purchase-order-pdf.ts.
--
-- The existing organisations table (from 0001_init.sql) had a hard
-- CHECK (code IN ('HOOKKA','OHANA')) which blocked any new sister
-- companies. We:
--   1. Drop that CHECK so new codes (HOUZS, etc) can be added.
--   2. Add the columns the new UI needs (msic_code, business_type,
--      letterhead_url, is_default, display_order, created_at, updated_at)
--      using IF NOT EXISTS so re-runs are safe.
--   3. Backfill org_id (tenant) for any pre-existing rows, then add the
--      unique (org_id, code) constraint.
--   4. Mark HOOKKA as the default org so the UI knows which one cannot
--      be deleted.
--   5. Add suppliers.purchase_org_code defaulting to 'HOOKKA' so existing
--      suppliers print with the existing default letterhead unchanged.
--
-- NOTE: org_id was added on this table by migration 0087_org_id_full_rollout
-- earlier — we just need the unique index here.

-- 1. Drop the legacy CHECK constraint. The exact constraint name is
--    auto-generated by Postgres; we look it up at runtime so this is
--    idempotent across staging/prod where the synthetic suffix may differ.
DO $$
DECLARE
  cn text;
BEGIN
  SELECT conname INTO cn
  FROM pg_constraint
  WHERE conrelid = 'organisations'::regclass
    AND contype  = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%code%HOOKKA%OHANA%';
  IF cn IS NOT NULL THEN
    EXECUTE format('ALTER TABLE organisations DROP CONSTRAINT %I', cn);
  END IF;
END $$;

-- 2. Make sure org_id (tenant) exists. 0087 already added it, but guard
--    here in case this migration runs in a different order on a fresh DB.
ALTER TABLE organisations
  ADD COLUMN IF NOT EXISTS org_id text NOT NULL DEFAULT 'hookka';

-- 3. New columns required by the registry UI.
ALTER TABLE organisations
  ADD COLUMN IF NOT EXISTS msic_code      text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS business_type  text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS letterhead_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_default     boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS display_order  integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at     text,
  ADD COLUMN IF NOT EXISTS updated_at     text;

-- 4. Backfill new columns for the two seeded rows so the UI cards render
--    cleanly even if nobody edits them.
UPDATE organisations
   SET msic_code     = COALESCE(NULLIF(msic_code, ''), msic, '31009'),
       business_type = 'Production & Manufacturing',
       is_default    = true,
       display_order = 0,
       created_at    = COALESCE(created_at, '2026-05-30T00:00:00Z'),
       updated_at    = COALESCE(updated_at, '2026-05-30T00:00:00Z')
 WHERE code = 'HOOKKA';

UPDATE organisations
   SET msic_code     = COALESCE(NULLIF(msic_code, ''), msic, '47591'),
       business_type = 'B2B Trading & Distribution',
       is_default    = false,
       display_order = 1,
       created_at    = COALESCE(created_at, '2026-05-30T00:00:00Z'),
       updated_at    = COALESCE(updated_at, '2026-05-30T00:00:00Z')
 WHERE code = 'OHANA';

-- 5. Unique (org_id, code) so the same tenant can't have two HOUZS rows
--    but different tenants can both have a HOOKKA.
CREATE UNIQUE INDEX IF NOT EXISTS organisations_code_per_org_uniq
  ON organisations (org_id, code);

CREATE INDEX IF NOT EXISTS idx_organisations_org_id
  ON organisations (org_id);

-- 6. Seed: ensure HOOKKA + OHANA rows exist even on a fresh DB where the
--    seed.sql path wasn't run. ON CONFLICT keeps the migration idempotent.
INSERT INTO organisations (
  id, org_id, code, name, reg_no, tin, msic, msic_code,
  phone, email, address, business_type,
  transfer_pricing_pct, is_active, is_default, display_order,
  created_at, updated_at
) VALUES
  ('org-hookka', 'hookka', 'HOOKKA',
   'HOOKKA INDUSTRIES SDN BHD',
   '202501060540 (1661946-X)', 'C60515534080', '31009', '31009',
   '+6011-6133 3173', 'finance@hookka.com',
   '2775F, Jalan Industri 12, Kampung Baru Sungai Buloh, 47000 Sungai Buloh, Selangor',
   'Production & Manufacturing',
   0, 1, true, 0,
   '2026-05-30T00:00:00Z', '2026-05-30T00:00:00Z'),
  ('org-ohana', 'hookka', 'OHANA',
   'OHANA MARKETING SDN BHD',
   '202501058806 (1660212-M)', 'C60508048080', '47591', '47591',
   '+6010-233 1323', 'ohanastudio99@gmail.com',
   'The Nest Residence, A-28-07 Jalan A Off, Jalan Puchong, 58200 Kuala Lumpur',
   'B2B Trading & Distribution',
   0, 1, false, 1,
   '2026-05-30T00:00:00Z', '2026-05-30T00:00:00Z')
ON CONFLICT (org_id, code) DO NOTHING;

-- 7. Add purchase_org_code to suppliers. Defaults to HOOKKA so existing
--    suppliers/POs print with the existing default letterhead unchanged.
ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS purchase_org_code text NOT NULL DEFAULT 'HOOKKA';

CREATE INDEX IF NOT EXISTS idx_suppliers_purchase_org_code
  ON suppliers (purchase_org_code);
