// ============================================================================
// generate-seed-sql.ts
//
// Walks every exported seed array in `src/lib/mock-data.ts` and emits the
// matching INSERT statements into `migrations/seed.sql`. Run with:
//     npx tsx scripts/generate-seed-sql.ts
//
// Re-run after bumping any mock-data. The generated file is deterministic —
// entities are written in dependency order so you can `wrangler d1 execute`
// it against a fresh D1 created from `migrations/0001_init.sql`.
// ============================================================================

import * as fs from "node:fs";
import * as path from "node:path";

import * as M from "../src/lib/mock-data";

// ---- SQL helpers ----------------------------------------------------------

const out: string[] = [];
let totalRows = 0;

function write(line: string): void {
  out.push(line);
}

function section(title: string): void {
  write("");
  write(`-- ========================================================`);
  write(`-- ${title}`);
  write(`-- ========================================================`);
}

/** Escape + quote a value for SQL. Numbers and booleans are inlined; strings
 *  get their single quotes doubled. `null` / `undefined` → NULL. */
function sqlVal(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) return "NULL";
    return String(v);
  }
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "bigint") return v.toString();
  if (v instanceof Date) return `'${v.toISOString()}'`;
  // Arrays / objects that we pass through as JSON blobs:
  if (typeof v === "object") {
    return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

/** Build an `INSERT INTO table (cols) VALUES (vals);` row. */
function insert(table: string, row: Record<string, unknown>): string {
  const cols = Object.keys(row);
  const vals = cols.map((c) => sqlVal(row[c]));
  return `INSERT INTO ${table} (${cols.join(", ")}) VALUES (${vals.join(", ")});`;
}

/** Emit a batch of rows + log progress. */
function emit(table: string, rows: Record<string, unknown>[]): void {
  if (rows.length === 0) {
    console.log(`Wrote 0 rows for ${table} (skipped empty)`);
    return;
  }
  for (const r of rows) write(insert(table, r));
  totalRows += rows.length;
  console.log(`Wrote ${rows.length} rows for ${table}`);
}

/** Bool → 0/1 (without clobbering already-numeric/null values). */
function b(v: unknown): number | null {
  if (v === undefined || v === null) return null;
  return v ? 1 : 0;
}

/** Coerce nullable optionals to null when missing. Also treats "" as null
 *  so empty-string FK references don't trigger constraint violations. */
function opt<T>(v: T | undefined | null): T | null {
  if (v === undefined || v === null) return null;
  if (typeof v === "string" && v === "") return null as unknown as T;
  return v;
}

// ---- Header --------------------------------------------------------------

write("-- Seed data for Hookka ERP — generated by scripts/generate-seed-sql.ts");
write("-- Regenerate with: npx tsx scripts/generate-seed-sql.ts");
// wrangler d1 execute --file wraps the whole file in a transaction, which
// silently disables `PRAGMA foreign_keys = OFF`. Use `defer_foreign_keys`
// instead — it postpones FK checks until COMMIT, which lets us insert
// children before parents when convenient.
write("BEGIN TRANSACTION;");
write("PRAGMA defer_foreign_keys = TRUE;");

// =============================================================================
// 1. MASTERS
// =============================================================================

section("Departments");
emit(
  "departments",
  M.departments.map((d) => ({
    id: d.id,
    code: d.code,
    name: d.name,
    shortName: d.shortName,
    sequence: d.sequence,
    color: d.color,
    workingHoursPerDay: d.workingHoursPerDay,
  })),
);

section("Customers + delivery hubs");
{
  const customerRows: Record<string, unknown>[] = [];
  const hubRows: Record<string, unknown>[] = [];
  for (const c of M.customers) {
    customerRows.push({
      id: c.id,
      code: c.code,
      name: c.name,
      ssmNo: opt(c.ssmNo),
      companyAddress: opt(c.companyAddress),
      creditTerms: opt(c.creditTerms),
      creditLimitSen: c.creditLimitSen,
      outstandingSen: c.outstandingSen,
      isActive: b(c.isActive),
      contactName: opt(c.contactName),
      phone: opt(c.phone),
      email: opt(c.email),
    });
    for (const h of c.deliveryHubs ?? []) {
      hubRows.push({
        id: h.id,
        customerId: c.id,
        code: h.code,
        shortName: h.shortName,
        state: h.state,
        address: h.address,
        contactName: h.contactName,
        phone: h.phone,
        email: h.email,
        isDefault: b(h.isDefault),
      });
    }
  }
  emit("customers", customerRows);
  emit("delivery_hubs", hubRows);
}

section("Customer hubs (hierarchical branch directory)");
emit(
  "customer_hubs",
  (M.customerHubs ?? []).map((h) => ({
    id: h.id,
    parentId: opt(h.parentId),
    creditorCode: h.creditorCode,
    name: h.name,
    shortName: h.shortName,
    state: h.state,
    pic: h.pic,
    picContact: h.picContact,
    picEmail: h.picEmail,
    deliveryAddress: h.deliveryAddress,
    isParent: b(h.isParent),
    children: h.children ?? null,
  })),
);

section("Products + BOM components + dept working times");
{
  const productRows: Record<string, unknown>[] = [];
  const bomRows: Record<string, unknown>[] = [];
  const dwtRows: Record<string, unknown>[] = [];
  const subRows: Record<string, unknown>[] = [];
  for (const p of M.products) {
    productRows.push({
      id: p.id,
      code: p.code,
      name: p.name,
      category: p.category,
      description: opt(p.description),
      baseModel: opt(p.baseModel),
      sizeCode: opt(p.sizeCode),
      sizeLabel: opt(p.sizeLabel),
      fabricUsage: p.fabricUsage,
      unitM3: p.unitM3,
      status: p.status,
      costPriceSen: p.costPriceSen,
      basePriceSen: opt(p.basePriceSen),
      price1Sen: opt(p.price1Sen),
      productionTimeMinutes: p.productionTimeMinutes,
      subAssemblies: p.subAssemblies ?? [],
      skuCode: opt(p.skuCode),
      fabricColor: opt(p.fabricColor),
      pieces: opt(p.pieces),
      seatHeightPrices: opt(p.seatHeightPrices),
    });
    for (const bom of p.bomComponents ?? []) {
      bomRows.push({
        id: bom.id,
        productId: p.id,
        materialCategory: bom.materialCategory,
        materialName: bom.materialName,
        qtyPerUnit: bom.qtyPerUnit,
        unit: bom.unit,
        wastePct: bom.wastePct,
      });
      for (const sub of bom.substitutes ?? []) {
        subRows.push({
          bomComponentId: bom.id,
          bomTemplateWipId: null,
          materialId: opt(sub.materialId),
          materialName: sub.materialName,
          materialCategory: opt(sub.materialCategory),
          costDiffPercent: sub.costDiffPercent,
          priority: sub.priority,
          notes: opt(sub.notes),
        });
      }
    }
    for (const w of p.deptWorkingTimes ?? []) {
      dwtRows.push({
        productId: p.id,
        departmentCode: w.departmentCode,
        minutes: w.minutes,
        category: w.category,
      });
    }
  }
  emit("products", productRows);
  emit("bom_components", bomRows);
  emit("material_substitutes", subRows);
  emit("dept_working_times", dwtRows);
}

section("Product dept configs");
emit(
  "product_dept_configs",
  (M.productDeptConfigs ?? []).map((c) => ({
    productCode: c.productCode,
    unitM3: c.unitM3,
    fabricUsage: c.fabricUsage,
    price2Sen: c.price2Sen,
    fabCutCategory: opt(c.fabCutCategory),
    fabCutMinutes: opt(c.fabCutMinutes),
    fabSewCategory: opt(c.fabSewCategory),
    fabSewMinutes: opt(c.fabSewMinutes),
    woodCutCategory: opt(c.woodCutCategory),
    woodCutMinutes: opt(c.woodCutMinutes),
    foamCategory: opt(c.foamCategory),
    foamMinutes: opt(c.foamMinutes),
    framingCategory: opt(c.framingCategory),
    framingMinutes: opt(c.framingMinutes),
    upholsteryCategory: opt(c.upholsteryCategory),
    upholsteryMinutes: opt(c.upholsteryMinutes),
    packingCategory: opt(c.packingCategory),
    packingMinutes: opt(c.packingMinutes),
    subAssemblies: c.subAssemblies ?? [],
    heightsSubAssemblies: c.heightsSubAssemblies ?? [],
  })),
);

section("Fabrics");
emit(
  "fabrics",
  (M.fabrics ?? []).map((f) => ({
    id: f.id,
    code: f.code,
    name: f.name,
    category: opt(f.category),
    priceSen: f.priceSen,
    sohMeters: f.sohMeters,
    reorderLevel: f.reorderLevel,
  })),
);

section("Fabric trackings");
emit(
  "fabric_trackings",
  (M.fabricTrackings ?? []).map((f) => ({
    id: f.id,
    fabricCode: f.fabricCode,
    fabricDescription: opt(f.fabricDescription),
    fabricCategory: opt(f.fabricCategory),
    priceTier: opt(f.priceTier),
    price: f.price,
    soh: f.soh,
    poOutstanding: f.poOutstanding,
    lastMonthUsage: f.lastMonthUsage,
    oneWeekUsage: f.oneWeekUsage,
    twoWeeksUsage: f.twoWeeksUsage,
    oneMonthUsage: f.oneMonthUsage,
    shortage: f.shortage,
    reorderPoint: f.reorderPoint,
    supplier: opt(f.supplier),
    leadTimeDays: f.leadTimeDays,
  })),
);

section("Raw materials");
emit(
  "raw_materials",
  (M.rawMaterials ?? []).map((r) => ({
    id: r.id,
    itemCode: r.itemCode,
    description: r.description,
    baseUOM: r.baseUOM,
    itemGroup: r.itemGroup,
    isActive: b(r.isActive),
    balanceQty: r.balanceQty,
  })),
);

section("Workers");
emit(
  "workers",
  (M.workers ?? []).map((w) => ({
    id: w.id,
    empNo: w.empNo,
    name: w.name,
    departmentId: opt(w.departmentId),
    departmentCode: opt(w.departmentCode),
    position: opt(w.position),
    phone: opt(w.phone),
    status: w.status,
    basicSalarySen: w.basicSalarySen,
    workingHoursPerDay: w.workingHoursPerDay,
    workingDaysPerMonth: w.workingDaysPerMonth,
    joinDate: opt(w.joinDate),
    icNumber: opt(w.icNumber),
    passportNumber: opt(w.passportNumber),
    nationality: opt(w.nationality),
  })),
);

section("Suppliers + materials");
{
  const supRows: Record<string, unknown>[] = [];
  const supMatRows: Record<string, unknown>[] = [];
  for (const s of M.suppliers ?? []) {
    supRows.push({
      id: s.id,
      code: s.code,
      name: s.name,
      contactPerson: opt(s.contactPerson),
      phone: opt(s.phone),
      email: opt(s.email),
      address: opt(s.address),
      state: opt(s.state),
      paymentTerms: opt(s.paymentTerms),
      status: s.status,
      rating: s.rating,
    });
    for (const m of s.materials ?? []) {
      supMatRows.push({
        supplierId: s.id,
        materialCategory: m.materialCategory,
        supplierSKU: m.supplierSKU,
        unitPriceSen: m.unitPriceSen,
        leadTimeDays: m.leadTimeDays,
        minOrderQty: m.minOrderQty,
        priority: m.priority,
      });
    }
  }
  emit("suppliers", supRows);
  emit("supplier_materials", supMatRows);
}

section("Supplier material bindings");
emit(
  "supplier_material_bindings",
  (M.supplierMaterialBindings ?? []).map((b0) => ({
    id: b0.id,
    supplierId: b0.supplierId,
    materialCode: b0.materialCode,
    materialName: b0.materialName,
    supplierSku: b0.supplierSku,
    unitPrice: b0.unitPrice,
    currency: b0.currency,
    leadTimeDays: b0.leadTimeDays,
    paymentTerms: b0.paymentTerms,
    moq: b0.moq,
    priceValidFrom: b0.priceValidFrom,
    priceValidTo: b0.priceValidTo,
    isMainSupplier: b(b0.isMainSupplier),
  })),
);

section("Price histories");
emit(
  "price_histories",
  (M.priceHistories ?? []).map((p) => ({
    id: p.id,
    bindingId: p.bindingId,
    supplierId: p.supplierId,
    materialCode: p.materialCode,
    oldPrice: p.oldPrice,
    newPrice: p.newPrice,
    currency: p.currency,
    changedDate: p.changedDate,
    changedBy: p.changedBy,
    reason: p.reason,
    approvalStatus: p.approvalStatus,
  })),
);

section("Supplier scorecards");
emit(
  "supplier_scorecards",
  (M.supplierScorecards ?? []).map((s) => ({
    supplierId: s.supplierId,
    onTimeRate: s.onTimeRate,
    qualityRate: s.qualityRate,
    leadTimeAccuracy: s.leadTimeAccuracy,
    avgPriceTrend: s.avgPriceTrend,
    overallRating: s.overallRating,
    lastUpdated: s.lastUpdated,
  })),
);

section("Organisations + inter-company config");
emit(
  "organisations",
  (M.organisations ?? []).map((o) => ({
    id: o.id,
    code: o.code,
    name: o.name,
    regNo: o.regNo,
    tin: o.tin,
    msic: o.msic,
    address: o.address,
    phone: o.phone,
    email: o.email,
    transferPricingPct: o.transferPricingPct,
    isActive: b(o.isActive),
  })),
);
if (M.interCompanyConfig) {
  emit("inter_company_config", [
    {
      id: 1,
      hookkaToOhanaRate: M.interCompanyConfig.hookkaToOhanaRate,
      autoCreateMirrorDocs: b(M.interCompanyConfig.autoCreateMirrorDocs),
      activeOrgId: opt((M as Record<string, unknown>).activeOrgId as string | undefined),
    },
  ]);
}

section("Pricing config lookups");
emit(
  "divan_height_options",
  (M.divanHeightOptions ?? []).map((o) => ({ height: o.height, surcharge: o.surcharge })),
);
emit(
  "leg_height_options",
  (M.legHeightOptions ?? []).map((o) => ({ height: o.height, surcharge: o.surcharge })),
);
emit(
  "special_order_options",
  (M.specialOrderOptions ?? []).map((o) => ({
    code: o.code,
    name: o.name,
    surcharge: o.surcharge,
    notes: o.notes,
  })),
);

section("Lorries / 3PL providers");
emit(
  "lorries",
  (M.lorries ?? []).map((l) => ({
    id: l.id,
    name: l.name,
    plateNumber: l.plateNumber,
    capacity: l.capacity,
    driverName: l.driverName,
    driverContact: l.driverContact,
    status: l.status,
  })),
);
emit(
  "three_pl_providers",
  (M.threePLProviders ?? []).map((t) => ({
    id: t.id,
    name: t.name,
    phone: t.phone,
    contactPerson: t.contactPerson,
    vehicleNo: t.vehicleNo,
    vehicleType: t.vehicleType,
    capacityM3: t.capacityM3,
    ratePerTripSen: t.ratePerTripSen,
    ratePerExtraDropSen: t.ratePerExtraDropSen,
    status: t.status,
    remarks: t.remarks,
    created_at: t.createdAt,
    updated_at: t.updatedAt,
  })),
);

// =============================================================================
// 2. TRANSACTIONS
// =============================================================================

// Sales orders are intentionally NOT seeded — the team enters them through
// the UI on a live instance. Skipping also keeps dependent tables
// (delivery_orders, invoices, production_orders, fg_units.soId) clean.

section("Purchase orders + items");
{
  const poRows: Record<string, unknown>[] = [];
  const itemRows: Record<string, unknown>[] = [];
  for (const po of M.purchaseOrders ?? []) {
    poRows.push({
      id: po.id,
      poNo: po.poNo,
      supplierId: po.supplierId,
      supplierName: opt(po.supplierName),
      subtotalSen: po.subtotalSen,
      totalSen: po.totalSen,
      status: po.status,
      orderDate: opt(po.orderDate),
      expectedDate: opt(po.expectedDate),
      receivedDate: opt(po.receivedDate),
      notes: opt(po.notes),
      created_at: po.createdAt,
      updated_at: po.updatedAt,
    });
    for (const it of po.items ?? []) {
      itemRows.push({
        id: it.id,
        purchaseOrderId: po.id,
        materialCategory: opt(it.materialCategory),
        materialName: opt(it.materialName),
        supplierSKU: opt(it.supplierSKU),
        quantity: it.quantity,
        unitPriceSen: it.unitPriceSen,
        totalSen: it.totalSen,
        receivedQty: it.receivedQty,
        unit: opt(it.unit),
      });
    }
  }
  emit("purchase_orders", poRows);
  emit("purchase_order_items", itemRows);
}

section("Delivery orders + items");
{
  const doRows: Record<string, unknown>[] = [];
  const itemRows: Record<string, unknown>[] = [];
  for (const d of M.deliveryOrders ?? []) {
    doRows.push({
      id: d.id,
      doNo: d.doNo,
      salesOrderId: opt(d.salesOrderId),
      companySO: opt(d.companySO),
      companySOId: opt(d.companySOId),
      customerId: d.customerId,
      customerPOId: opt(d.customerPOId),
      customerName: d.customerName,
      customerState: opt(d.customerState),
      hubId: opt(d.hubId),
      hubName: opt(d.hubName),
      deliveryAddress: opt(d.deliveryAddress),
      contactPerson: opt(d.contactPerson),
      contactPhone: opt(d.contactPhone),
      deliveryDate: opt(d.deliveryDate),
      hookkaExpectedDD: opt(d.hookkaExpectedDD),
      driverId: opt(d.driverId),
      driverName: opt(d.driverName),
      vehicleNo: opt(d.vehicleNo),
      totalM3: d.totalM3,
      totalItems: d.totalItems,
      status: d.status,
      overdue: opt(d.overdue),
      dispatchedAt: opt(d.dispatchedAt),
      deliveredAt: opt(d.deliveredAt),
      remarks: opt(d.remarks),
      dropPoints: opt(d.dropPoints),
      deliveryCostSen: opt(d.deliveryCostSen),
      lorryId: opt(d.lorryId),
      lorryName: opt(d.lorryName),
      doQrCode: opt(d.doQrCode),
      fgUnitIds: d.fgUnitIds ?? null,
      signedAt: opt(d.signedAt),
      signedByWorkerId: opt(d.signedByWorkerId),
      signedByWorkerName: opt(d.signedByWorkerName),
      proofOfDelivery: opt(d.proofOfDelivery),
      created_at: d.createdAt,
      updated_at: d.updatedAt,
    });
    for (const it of d.items ?? []) {
      itemRows.push({
        id: it.id,
        deliveryOrderId: d.id,
        productionOrderId: opt(it.productionOrderId),
        poNo: opt(it.poNo),
        productCode: opt(it.productCode),
        productName: opt(it.productName),
        sizeLabel: opt(it.sizeLabel),
        fabricCode: opt(it.fabricCode),
        quantity: it.quantity,
        itemM3: it.itemM3,
        rackingNumber: opt(it.rackingNumber),
        packingStatus: opt(it.packingStatus),
        salesOrderNo: opt(it.salesOrderNo),
      });
    }
  }
  emit("delivery_orders", doRows);
  emit("delivery_order_items", itemRows);
}

section("Invoices + items + payments");
{
  const invRows: Record<string, unknown>[] = [];
  const itemRows: Record<string, unknown>[] = [];
  const payRows: Record<string, unknown>[] = [];
  for (const i of M.invoices ?? []) {
    invRows.push({
      id: i.id,
      invoiceNo: i.invoiceNo,
      deliveryOrderId: opt(i.deliveryOrderId),
      doNo: opt(i.doNo),
      salesOrderId: opt(i.salesOrderId),
      companySOId: opt(i.companySOId),
      customerId: i.customerId,
      customerName: i.customerName,
      customerState: opt(i.customerState),
      hubId: opt(i.hubId),
      hubName: opt(i.hubName),
      subtotalSen: i.subtotalSen,
      totalSen: i.totalSen,
      status: i.status,
      invoiceDate: opt(i.invoiceDate),
      dueDate: opt(i.dueDate),
      paidAmount: i.paidAmount,
      paymentDate: opt(i.paymentDate),
      paymentMethod: opt(i.paymentMethod),
      notes: opt(i.notes),
      created_at: i.createdAt,
      updated_at: i.updatedAt,
    });
    for (const it of i.items ?? []) {
      itemRows.push({
        id: it.id,
        invoiceId: i.id,
        productCode: opt(it.productCode),
        productName: opt(it.productName),
        sizeLabel: opt(it.sizeLabel),
        fabricCode: opt(it.fabricCode),
        quantity: it.quantity,
        unitPriceSen: it.unitPriceSen,
        totalSen: it.totalSen,
      });
    }
    for (const p of i.payments ?? []) {
      payRows.push({
        id: p.id,
        invoiceId: i.id,
        date: p.date,
        amountSen: p.amountSen,
        method: p.method,
        reference: p.reference,
      });
    }
  }
  emit("invoices", invRows);
  emit("invoice_items", itemRows);
  emit("invoice_payments", payRows);
}

section("Credit notes");
emit(
  "credit_notes",
  (M.creditNotes ?? []).map((c) => ({
    id: c.id,
    noteNumber: c.noteNumber,
    invoiceId: opt(c.invoiceId),
    invoiceNumber: opt(c.invoiceNumber),
    customerId: c.customerId,
    customerName: c.customerName,
    date: c.date,
    reason: c.reason,
    reasonDetail: c.reasonDetail,
    totalAmount: c.totalAmount,
    status: c.status,
    approvedBy: opt(c.approvedBy),
    items: c.items ?? [],
  })),
);

section("Debit notes");
emit(
  "debit_notes",
  (M.debitNotes ?? []).map((d) => ({
    id: d.id,
    noteNumber: d.noteNumber,
    invoiceId: opt(d.invoiceId),
    invoiceNumber: opt(d.invoiceNumber),
    customerId: d.customerId,
    customerName: d.customerName,
    date: d.date,
    reason: d.reason,
    reasonDetail: d.reasonDetail,
    totalAmount: d.totalAmount,
    status: d.status,
    approvedBy: opt(d.approvedBy),
    items: d.items ?? [],
  })),
);

section("Payment records");
emit(
  "payment_records",
  (M.paymentRecords ?? []).map((p) => ({
    id: p.id,
    receiptNumber: p.receiptNumber,
    customerId: p.customerId,
    customerName: p.customerName,
    date: p.date,
    amount: p.amount,
    method: p.method,
    reference: p.reference,
    status: p.status,
    allocations: p.allocations ?? [],
  })),
);

section("E-Invoices");
emit(
  "e_invoices",
  (M.eInvoices ?? []).map((e) => ({
    id: e.id,
    invoiceId: opt(e.invoiceId),
    invoiceNo: e.invoiceNo,
    customerName: opt(e.customerName),
    customerTIN: opt(e.customerTIN),
    submissionId: opt(e.submissionId),
    uuid: opt(e.uuid),
    status: e.status,
    submittedAt: opt(e.submittedAt),
    validatedAt: opt(e.validatedAt),
    errorMessage: opt(e.errorMessage),
    xmlContent: opt(e.xmlContent),
    totalExcludingTax: e.totalExcludingTax,
    taxAmount: e.taxAmount,
    totalIncludingTax: e.totalIncludingTax,
    created_at: e.createdAt,
  })),
);

// =============================================================================
// 3. PRODUCTION
// =============================================================================

section("Production orders + job cards + piece pics");
{
  const poRows: Record<string, unknown>[] = [];
  const jcRows: Record<string, unknown>[] = [];
  const ppRows: Record<string, unknown>[] = [];
  for (const po of M.productionOrders ?? []) {
    poRows.push({
      id: po.id,
      poNo: po.poNo,
      salesOrderId: opt(po.salesOrderId),
      salesOrderNo: opt(po.salesOrderNo),
      lineNo: po.lineNo,
      customerPOId: opt(po.customerPOId),
      customerReference: opt(po.customerReference),
      customerName: opt(po.customerName),
      customerState: opt(po.customerState),
      companySOId: opt(po.companySOId),
      productId: opt(po.productId),
      productCode: opt(po.productCode),
      productName: opt(po.productName),
      itemCategory: opt(po.itemCategory),
      sizeCode: opt(po.sizeCode),
      sizeLabel: opt(po.sizeLabel),
      fabricCode: opt(po.fabricCode),
      quantity: po.quantity,
      gapInches: opt(po.gapInches),
      divanHeightInches: opt(po.divanHeightInches),
      legHeightInches: opt(po.legHeightInches),
      specialOrder: opt(po.specialOrder),
      notes: opt(po.notes),
      status: po.status,
      currentDepartment: opt(po.currentDepartment),
      progress: po.progress,
      startDate: opt(po.startDate),
      targetEndDate: opt(po.targetEndDate),
      completedDate: opt(po.completedDate),
      rackingNumber: opt(po.rackingNumber),
      stockedIn: b(po.stockedIn),
      created_at: po.createdAt,
      updated_at: po.updatedAt,
    });
    for (const jc of po.jobCards ?? []) {
      jcRows.push({
        id: jc.id,
        productionOrderId: po.id,
        departmentId: opt(jc.departmentId),
        departmentCode: opt(jc.departmentCode),
        departmentName: opt(jc.departmentName),
        sequence: jc.sequence,
        status: jc.status,
        dueDate: opt(jc.dueDate),
        wipKey: opt(jc.wipKey),
        wipCode: opt(jc.wipCode),
        wipType: opt(jc.wipType),
        wipLabel: opt(jc.wipLabel),
        wipQty: opt(jc.wipQty),
        prerequisiteMet: b(jc.prerequisiteMet),
        pic1Id: opt(jc.pic1Id),
        pic1Name: opt(jc.pic1Name),
        pic2Id: opt(jc.pic2Id),
        pic2Name: opt(jc.pic2Name),
        completedDate: opt(jc.completedDate),
        estMinutes: jc.estMinutes,
        actualMinutes: opt(jc.actualMinutes),
        category: opt(jc.category),
        productionTimeMinutes: jc.productionTimeMinutes,
        overdue: opt(jc.overdue),
        rackingNumber: opt(jc.rackingNumber),
      });
      for (const pp of (jc as unknown as { piecePics?: M.PiecePic[] }).piecePics ?? []) {
        ppRows.push({
          jobCardId: jc.id,
          pieceNo: pp.pieceNo,
          pic1Id: opt(pp.pic1Id),
          pic1Name: opt(pp.pic1Name),
          pic2Id: opt(pp.pic2Id),
          pic2Name: opt(pp.pic2Name),
          completedAt: opt(pp.completedAt),
          lastScanAt: opt(pp.lastScanAt),
          boundStickerKey: opt(pp.boundStickerKey),
        });
      }
    }
  }
  emit("production_orders", poRows);
  emit("job_cards", jcRows);
  emit("piece_pics", ppRows);
}

section("WIP items");
emit(
  "wip_items",
  (M.wipItems ?? []).map((w) => ({
    id: w.id,
    code: w.code,
    type: w.type,
    relatedProduct: w.relatedProduct,
    deptStatus: w.deptStatus,
    stockQty: w.stockQty,
    status: w.status,
  })),
);

section("FG units + scan history");
{
  const fgRows: Record<string, unknown>[] = [];
  const histRows: Record<string, unknown>[] = [];
  for (const f of M.fgUnits ?? []) {
    fgRows.push({
      id: f.id,
      unitSerial: f.unitSerial,
      shortCode: opt(f.shortCode),
      soId: opt(f.soId),
      soNo: opt(f.soNo),
      soLineNo: opt(f.soLineNo),
      poId: opt(f.poId),
      poNo: opt(f.poNo),
      productCode: opt(f.productCode),
      productName: opt(f.productName),
      unitNo: opt(f.unitNo),
      totalUnits: opt(f.totalUnits),
      pieceNo: opt(f.pieceNo),
      totalPieces: opt(f.totalPieces),
      pieceName: opt(f.pieceName),
      customerName: opt(f.customerName),
      customerHub: opt(f.customerHub),
      mfdDate: opt(f.mfdDate),
      status: f.status,
      packerId: opt(f.packerId),
      packerName: opt(f.packerName),
      packedAt: opt(f.packedAt),
      loadedAt: opt(f.loadedAt),
      deliveredAt: opt(f.deliveredAt),
      returnedAt: opt(f.returnedAt),
      batchId: opt(f.batchId),
      sourcePieceIndex: opt(f.sourcePieceIndex),
      sourceSlotIndex: opt(f.sourceSlotIndex),
      upholsteredBy: opt(f.upholsteredBy),
      upholsteredByName: opt(f.upholsteredByName),
      upholsteredAt: opt(f.upholsteredAt),
      doId: opt(f.doId),
    });
    for (const s of f.scanHistory ?? []) {
      histRows.push({
        fgUnitId: f.id,
        timestamp: s.timestamp,
        deptCode: s.deptCode,
        workerId: opt(s.workerId),
        workerName: opt(s.workerName),
        picSlot: opt(s.picSlot),
        action: s.action,
        sourceBatchId: opt(s.sourceBatchId),
        sourcePieceIndex: opt(s.sourcePieceIndex),
        sourceSlotIndex: opt(s.sourceSlotIndex),
        note: opt(s.note),
      });
    }
  }
  emit("fg_units", fgRows);
  emit("fg_scan_history", histRows);
}

section("RM batches, FG batches, cost ledger");
emit(
  "rm_batches",
  (M.rmBatches ?? []).map((r) => ({
    id: r.id,
    rmId: r.rmId,
    source: r.source,
    sourceRefId: opt(r.sourceRefId),
    receivedDate: r.receivedDate,
    originalQty: r.originalQty,
    remainingQty: r.remainingQty,
    unitCostSen: r.unitCostSen,
    created_at: r.createdAt,
    notes: opt(r.notes),
  })),
);
emit(
  "fg_batches",
  (M.fgBatches ?? []).map((f) => ({
    id: f.id,
    productId: f.productId,
    productionOrderId: opt(f.productionOrderId),
    completedDate: f.completedDate,
    originalQty: f.originalQty,
    remainingQty: f.remainingQty,
    unitCostSen: f.unitCostSen,
    materialCostSen: f.materialCostSen,
    laborCostSen: f.laborCostSen,
    overheadCostSen: f.overheadCostSen,
    created_at: f.createdAt,
  })),
);
emit(
  "cost_ledger",
  (M.costLedger ?? []).map((c) => ({
    id: c.id,
    date: c.date,
    type: c.type,
    itemType: c.itemType,
    itemId: c.itemId,
    batchId: opt(c.batchId),
    qty: c.qty,
    direction: c.direction,
    unitCostSen: c.unitCostSen,
    totalCostSen: c.totalCostSen,
    refType: opt(c.refType),
    refId: opt(c.refId),
    notes: opt(c.notes),
  })),
);

section("Rack locations + rack items + stock movements");
{
  const rlRows: Record<string, unknown>[] = [];
  const riRows: Record<string, unknown>[] = [];
  for (const r of M.rackLocations ?? []) {
    rlRows.push({
      id: r.id,
      rack: r.rack,
      position: opt(r.position),
      status: r.status,
      reserved: r.reserved === undefined ? null : b(r.reserved),
      productionOrderId: opt(r.productionOrderId),
      productCode: opt(r.productCode),
      productName: opt(r.productName),
      sizeLabel: opt(r.sizeLabel),
      customerName: opt(r.customerName),
      stockedInDate: opt(r.stockedInDate),
      notes: opt(r.notes),
    });
    for (const it of r.items ?? []) {
      riRows.push({
        rackLocationId: r.id,
        productionOrderId: opt(it.productionOrderId),
        productCode: it.productCode,
        productName: opt(it.productName),
        sizeLabel: opt(it.sizeLabel),
        customerName: opt(it.customerName),
        qty: opt(it.qty),
        stockedInDate: opt(it.stockedInDate),
        notes: opt(it.notes),
      });
    }
  }
  emit("rack_locations", rlRows);
  emit("rack_items", riRows);
}
emit(
  "stock_movements",
  (M.stockMovements ?? []).map((s) => ({
    id: s.id,
    type: s.type,
    rackLocationId: opt(s.rackLocationId),
    rackLabel: s.rackLabel,
    productionOrderId: opt(s.productionOrderId),
    productCode: s.productCode,
    productName: s.productName,
    quantity: s.quantity,
    reason: s.reason,
    performedBy: s.performedBy,
    created_at: s.createdAt,
  })),
);

section("GRNs + items");
{
  const grnRows: Record<string, unknown>[] = [];
  const itemRows: Record<string, unknown>[] = [];
  for (const g of M.grns ?? []) {
    grnRows.push({
      id: g.id,
      grnNumber: g.grnNumber,
      poId: opt(g.poId),
      poNumber: opt(g.poNumber),
      supplierId: opt(g.supplierId),
      supplierName: opt(g.supplierName),
      receiveDate: opt(g.receiveDate),
      receivedBy: opt(g.receivedBy),
      totalAmount: g.totalAmount,
      qcStatus: g.qcStatus,
      status: g.status,
      notes: opt(g.notes),
    });
    for (const it of g.items ?? []) {
      itemRows.push({
        grnId: g.id,
        poItemIndex: it.poItemIndex,
        materialCode: it.materialCode,
        materialName: it.materialName,
        orderedQty: it.orderedQty,
        receivedQty: it.receivedQty,
        acceptedQty: it.acceptedQty,
        rejectedQty: it.rejectedQty,
        rejectionReason: opt(it.rejectionReason),
        unitPrice: it.unitPrice,
      });
    }
  }
  emit("grns", grnRows);
  emit("grn_items", itemRows);
}

section("Three-way matches");
emit(
  "three_way_matches",
  (M.threeWayMatches ?? []).map((t) => ({
    id: t.id,
    poId: opt(t.poId),
    poNumber: opt(t.poNumber),
    grnId: opt(t.grnId),
    grnNumber: opt(t.grnNumber),
    invoiceId: opt(t.invoiceId),
    invoiceNumber: opt(t.invoiceNumber),
    supplierId: opt(t.supplierId),
    supplierName: opt(t.supplierName),
    matchStatus: t.matchStatus,
    poTotal: t.poTotal,
    grnTotal: t.grnTotal,
    invoiceTotal: opt(t.invoiceTotal),
    variance: t.variance,
    variancePercent: t.variancePercent,
    withinTolerance: b(t.withinTolerance),
    items: t.items ?? [],
  })),
);

section("Goods in transit");
emit(
  "goods_in_transit",
  (M.goodsInTransit ?? []).map((g) => ({
    id: g.id,
    poId: opt(g.poId),
    poNumber: opt(g.poNumber),
    supplierId: opt(g.supplierId),
    supplierName: opt(g.supplierName),
    shippingMethod: g.shippingMethod,
    containerNumber: opt(g.containerNumber),
    trackingNumber: opt(g.trackingNumber),
    carrierName: g.carrierName,
    status: g.status,
    orderDate: g.orderDate,
    shippedDate: opt(g.shippedDate),
    expectedArrival: g.expectedArrival,
    actualArrival: opt(g.actualArrival),
    customsClearanceDate: opt(g.customsClearanceDate),
    customsStatus: g.customsStatus,
    currency: g.currency,
    productCost: g.productCost,
    shippingCost: g.shippingCost,
    customsDuty: g.customsDuty,
    exchangeRate: opt(g.exchangeRate),
    landedCost: g.landedCost,
    items: g.items ?? [],
    notes: opt(g.notes),
  })),
);

// =============================================================================
// 4. ACCOUNTING
// =============================================================================

section("Chart of accounts");
{
  // Parents first so FK check passes (self-ref). The seed data is already
  // roughly in top-down order (100-0000 before 100-0001, etc.) but sort on
  // parentCode presence just to be safe.
  const rows = [...(M.chartOfAccounts ?? [])].sort((a, b0) => {
    const aHasParent = a.parentCode ? 1 : 0;
    const bHasParent = b0.parentCode ? 1 : 0;
    return aHasParent - bHasParent;
  });
  emit(
    "chart_of_accounts",
    rows.map((a) => ({
      code: a.code,
      name: a.name,
      type: a.type,
      parentCode: opt(a.parentCode),
      balance: a.balance,
      isActive: b(a.isActive),
    })),
  );
}

section("Journal entries + lines");
{
  const jeRows: Record<string, unknown>[] = [];
  const lineRows: Record<string, unknown>[] = [];
  for (const j of M.journalEntries ?? []) {
    jeRows.push({
      id: j.id,
      entryNo: j.entryNo,
      date: j.date,
      description: j.description,
      status: j.status,
      createdBy: j.createdBy,
      created_at: j.createdAt,
    });
    for (const l of j.lines ?? []) {
      lineRows.push({
        journalEntryId: j.id,
        accountCode: l.accountCode,
        accountName: opt(l.accountName),
        debitSen: l.debitSen,
        creditSen: l.creditSen,
        description: opt(l.description),
      });
    }
  }
  emit("journal_entries", jeRows);
  emit("journal_lines", lineRows);
}

section("AR / AP aging");
emit(
  "ar_aging",
  (M.arAging ?? []).map((a) => ({
    customerId: a.customerId,
    customerName: a.customerName,
    currentSen: a.currentSen,
    days30Sen: a.days30Sen,
    days60Sen: a.days60Sen,
    days90Sen: a.days90Sen,
    over90Sen: a.over90Sen,
  })),
);
emit(
  "ap_aging",
  (M.apAging ?? []).map((a) => ({
    supplierId: a.supplierId,
    supplierName: a.supplierName,
    currentSen: a.currentSen,
    days30Sen: a.days30Sen,
    days60Sen: a.days60Sen,
    days90Sen: a.days90Sen,
    over90Sen: a.over90Sen,
  })),
);

section("Bank accounts + transactions");
emit(
  "bank_accounts",
  (M.bankAccounts ?? []).map((b0) => ({
    id: b0.id,
    bankName: b0.bankName,
    accountNo: b0.accountNo,
    accountName: b0.accountName,
    balanceSen: b0.balanceSen,
    currency: b0.currency,
  })),
);
emit(
  "bank_transactions",
  (M.bankTransactions ?? []).map((t) => ({
    id: t.id,
    bankAccountId: t.bankAccountId,
    date: t.date,
    description: t.description,
    amountSen: t.amountSen,
    type: t.type,
    reference: t.reference,
    isReconciled: b(t.isReconciled),
    matchedJournalId: opt(t.matchedJournalId),
  })),
);

section("P&L + Balance sheet entries");
emit(
  "pl_entries",
  (M.plEntries ?? []).map((p) => ({
    id: p.id,
    period: p.period,
    accountCode: p.accountCode,
    accountName: p.accountName,
    category: p.category,
    amount: p.amount,
    productCategory: opt(p.productCategory),
    customerId: opt(p.customerId),
    customerName: opt(p.customerName),
    state: opt(p.state),
  })),
);
emit(
  "balance_sheet_entries",
  (M.balanceSheetEntries ?? []).map((b0) => ({
    id: b0.id,
    accountCode: b0.accountCode,
    accountName: b0.accountName,
    category: b0.category,
    balance: b0.balance,
    asOfDate: b0.asOfDate,
  })),
);

section("Stock accounts + monthly stock values");
emit(
  "stock_accounts",
  (M.stockAccounts ?? []).map((s) => ({
    code: s.code,
    description: s.description,
    category: s.category,
  })),
);
emit(
  "monthly_stock_values",
  (M.monthlyStockValues ?? []).map((m) => ({
    id: m.id,
    period: m.period,
    accountCode: m.accountCode,
    accountDescription: m.accountDescription,
    openingValue: m.openingValue,
    purchasesValue: m.purchasesValue,
    consumptionValue: m.consumptionValue,
    closingValue: m.closingValue,
    physicalCountValue: opt(m.physicalCountValue),
    variancePercent: opt(m.variancePercent),
    status: m.status,
    postedDate: opt(m.postedDate),
    postedBy: opt(m.postedBy),
  })),
);

// =============================================================================
// 5. SUPPORTING
// =============================================================================

section("Attendance records");
emit(
  "attendance_records",
  (M.attendanceRecords ?? []).map((a) => ({
    id: a.id,
    employeeId: a.employeeId,
    employeeName: a.employeeName,
    departmentCode: a.departmentCode,
    departmentName: a.departmentName,
    date: a.date,
    clockIn: opt(a.clockIn),
    clockOut: opt(a.clockOut),
    status: a.status,
    workingMinutes: a.workingMinutes,
    productionTimeMinutes: a.productionTimeMinutes,
    efficiencyPct: a.efficiencyPct,
    overtimeMinutes: a.overtimeMinutes,
    deptBreakdown: a.deptBreakdown ?? [],
    notes: a.notes,
  })),
);

section("Leave records");
emit(
  "leave_records",
  (M.leaveRecords ?? []).map((l) => ({
    id: l.id,
    workerId: l.workerId,
    workerName: l.workerName,
    type: l.type,
    startDate: l.startDate,
    endDate: l.endDate,
    days: l.days,
    status: l.status,
    reason: l.reason,
    approvedBy: opt(l.approvedBy),
  })),
);

section("Payroll records + payslip details");
emit(
  "payroll_records",
  (M.payrollRecords ?? []).map((p) => ({
    id: p.id,
    workerId: p.workerId,
    workerName: p.workerName,
    period: p.period,
    basicSalarySen: p.basicSalarySen,
    workingDays: p.workingDays,
    otHoursWeekday: p.otHoursWeekday,
    otHoursSunday: p.otHoursSunday,
    otHoursHoliday: p.otHoursHoliday,
    otAmountSen: p.otAmountSen,
    grossSalarySen: p.grossSalarySen,
    epfEmployeeSen: p.epfEmployeeSen,
    epfEmployerSen: p.epfEmployerSen,
    socsoEmployeeSen: p.socsoEmployeeSen,
    socsoEmployerSen: p.socsoEmployerSen,
    eisEmployeeSen: p.eisEmployeeSen,
    eisEmployerSen: p.eisEmployerSen,
    pcbSen: p.pcbSen,
    totalDeductionsSen: p.totalDeductionsSen,
    netPaySen: p.netPaySen,
    status: p.status,
  })),
);
emit(
  "payslip_details",
  (M.payslipDetails ?? []).map((p) => ({
    id: p.id,
    employeeId: p.employeeId,
    employeeName: p.employeeName,
    employeeNo: p.employeeNo,
    departmentCode: p.departmentCode,
    period: p.period,
    basicSalary: p.basicSalary,
    workingDays: p.workingDays,
    otWeekdayHours: p.otWeekdayHours,
    otSundayHours: p.otSundayHours,
    otPHHours: p.otPHHours,
    hourlyRate: p.hourlyRate,
    otWeekdayAmount: p.otWeekdayAmount,
    otSundayAmount: p.otSundayAmount,
    otPHAmount: p.otPHAmount,
    totalOT: p.totalOT,
    allowances: p.allowances,
    grossPay: p.grossPay,
    epfEmployee: p.epfEmployee,
    epfEmployer: p.epfEmployer,
    socsoEmployee: p.socsoEmployee,
    socsoEmployer: p.socsoEmployer,
    eisEmployee: p.eisEmployee,
    eisEmployer: p.eisEmployer,
    pcb: p.pcb,
    totalDeductions: p.totalDeductions,
    netPay: p.netPay,
    bankAccount: p.bankAccount,
    status: p.status,
  })),
);

section("Approval requests");
emit(
  "approval_requests",
  (M.approvalRequests ?? []).map((a) => ({
    id: a.id,
    type: a.type,
    referenceNo: opt(a.referenceNo),
    referenceId: opt(a.referenceId),
    title: a.title,
    description: opt(a.description),
    requestedBy: opt(a.requestedBy),
    requestedAt: opt(a.requestedAt),
    status: a.status,
    approvedBy: opt(a.approvedBy),
    approvedAt: opt(a.approvedAt),
    reason: opt(a.reason),
    amountSen: opt((a as unknown as { amountSen?: number }).amountSen),
    metadata: opt((a as unknown as { metadata?: Record<string, string> }).metadata),
  })),
);

section("QC inspections + defects");
{
  const insp: Record<string, unknown>[] = [];
  const defects: Record<string, unknown>[] = [];
  for (const q of M.qcInspections ?? []) {
    insp.push({
      id: q.id,
      inspectionNo: q.inspectionNo,
      productionOrderId: opt(q.productionOrderId),
      poNo: opt(q.poNo),
      productCode: opt(q.productCode),
      productName: opt(q.productName),
      customerName: opt(q.customerName),
      department: opt(q.department),
      inspectorId: opt(q.inspectorId),
      inspectorName: opt(q.inspectorName),
      result: q.result,
      notes: opt(q.notes),
      inspectionDate: opt(q.inspectionDate),
      created_at: q.createdAt,
    });
    for (const d of q.defects ?? []) {
      defects.push({
        id: d.id,
        qcInspectionId: q.id,
        type: d.type,
        severity: d.severity,
        description: d.description,
        actionTaken: d.actionTaken,
      });
    }
  }
  emit("qc_inspections", insp);
  emit("qc_defects", defects);
}

section("R&D projects + prototypes");
{
  const projRows: Record<string, unknown>[] = [];
  const protoRows: Record<string, unknown>[] = [];
  for (const p of M.rdProjects ?? []) {
    projRows.push({
      id: p.id,
      code: p.code,
      name: p.name,
      description: p.description,
      projectType: (p as unknown as { projectType?: string }).projectType ?? null,
      productCategory: p.productCategory,
      serviceId: opt((p as unknown as { serviceId?: string }).serviceId),
      currentStage: p.currentStage,
      targetLaunchDate: p.targetLaunchDate,
      assignedTeam: p.assignedTeam ?? [],
      totalBudget: p.totalBudget,
      actualCost: p.actualCost,
      milestones: p.milestones ?? [],
      productionBOM: (p as unknown as { productionBOM?: unknown[] }).productionBOM ?? null,
      materialIssuances: (p as unknown as { materialIssuances?: unknown[] }).materialIssuances ?? null,
      labourLogs: (p as unknown as { labourLogs?: unknown[] }).labourLogs ?? null,
      createdDate: p.createdDate,
      status: p.status,
    });
    for (const proto of p.prototypes ?? []) {
      protoRows.push({
        id: proto.id,
        projectId: p.id,
        prototypeType: (proto as unknown as { prototypeType?: string }).prototypeType ?? null,
        version: proto.version,
        description: proto.description,
        materialsCost: proto.materialsCost,
        labourHours: proto.labourHours,
        testResults: proto.testResults,
        feedback: proto.feedback,
        improvements: (proto as unknown as { improvements?: string }).improvements ?? null,
        defects: (proto as unknown as { defects?: string }).defects ?? null,
        createdDate: proto.createdDate,
      });
    }
  }
  emit("rd_projects", projRows);
  emit("rd_prototypes", protoRows);
}

section("Equipment + maintenance logs");
emit(
  "equipment_list",
  (M.equipmentList ?? []).map((e) => ({
    id: e.id,
    code: e.code,
    name: e.name,
    department: e.department,
    type: e.type,
    status: e.status,
    lastMaintenanceDate: e.lastMaintenanceDate,
    nextMaintenanceDate: e.nextMaintenanceDate,
    maintenanceCycleDays: e.maintenanceCycleDays,
    purchaseDate: e.purchaseDate,
    notes: e.notes,
  })),
);
emit(
  "maintenance_logs",
  (M.maintenanceLogs ?? []).map((m) => ({
    id: m.id,
    equipmentId: m.equipmentId,
    equipmentName: m.equipmentName,
    type: m.type,
    description: m.description,
    performedBy: m.performedBy,
    date: m.date,
    costSen: m.costSen,
    downtimeHours: m.downtimeHours,
  })),
);

section("Consignment notes + items");
{
  const noteRows: Record<string, unknown>[] = [];
  const itemRows: Record<string, unknown>[] = [];
  for (const c of M.consignmentNotes ?? []) {
    noteRows.push({
      id: c.id,
      noteNumber: c.noteNumber,
      type: c.type,
      customerId: c.customerId,
      customerName: c.customerName,
      branchName: c.branchName,
      sentDate: c.sentDate,
      status: c.status,
      totalValue: c.totalValue,
      notes: c.notes,
    });
    for (const it of c.items ?? []) {
      itemRows.push({
        id: it.id,
        consignmentNoteId: c.id,
        productId: it.productId,
        productName: it.productName,
        productCode: it.productCode,
        quantity: it.quantity,
        unitPrice: it.unitPrice,
        status: it.status,
        soldDate: opt(it.soldDate),
        returnedDate: opt(it.returnedDate),
      });
    }
  }
  emit("consignment_notes", noteRows);
  emit("consignment_items", itemRows);
}

section("Notifications");
emit(
  "notifications",
  (M.notifications ?? []).map((n) => ({
    id: n.id,
    type: n.type,
    title: n.title,
    message: n.message,
    severity: n.severity,
    isRead: b(n.isRead),
    link: opt(n.link),
    created_at: n.createdAt,
  })),
);

section("MRP runs + requirements");
{
  const runRows: Record<string, unknown>[] = [];
  const reqRows: Record<string, unknown>[] = [];
  for (const r of M.mrpRuns ?? []) {
    runRows.push({
      id: r.id,
      runDate: r.runDate,
      planningHorizon: r.planningHorizon,
      productionOrderCount: r.productionOrderCount,
      totalMaterials: r.totalMaterials,
      shortageCount: r.shortageCount,
      status: r.status,
    });
    for (const q of r.requirements ?? []) {
      reqRows.push({
        id: q.id,
        mrpRunId: r.id,
        materialName: q.materialName,
        materialCategory: q.materialCategory,
        unit: q.unit,
        grossRequired: q.grossRequired,
        onHand: q.onHand,
        onOrder: q.onOrder,
        netRequired: q.netRequired,
        status: q.status,
        suggestedPOQty: q.suggestedPOQty,
        preferredSupplierId: opt(q.preferredSupplierId),
        preferredSupplierName: opt(q.preferredSupplierName),
      });
    }
  }
  emit("mrp_runs", runRows);
  emit("mrp_requirements", reqRows);
}

section("Historical sales + forecast entries + promise dates");
emit(
  "historical_sales",
  (M.historicalSales ?? []).map((h) => ({
    productId: h.productId,
    productCode: h.productCode,
    productName: h.productName,
    period: h.period,
    quantity: h.quantity,
    revenue: h.revenue,
    customerId: h.customerId,
    customerName: h.customerName,
  })),
);
emit(
  "forecast_entries",
  (M.forecastEntries ?? []).map((f) => ({
    id: f.id,
    productId: f.productId,
    productName: f.productName,
    productCode: f.productCode,
    period: f.period,
    forecastQty: f.forecastQty,
    actualQty: opt(f.actualQty),
    method: f.method,
    confidence: f.confidence,
    createdDate: f.createdDate,
  })),
);
emit(
  "promise_date_calcs",
  (M.promiseDateCalcs ?? []).map((p) => ({
    productId: p.productId,
    currentQueueDays: p.currentQueueDays,
    materialAvailability: p.materialAvailability,
    estimatedCompletionDays: p.estimatedCompletionDays,
    promiseDate: p.promiseDate,
  })),
);

section("Dept lead times + schedule entries");
emit(
  "dept_lead_times",
  (M.deptLeadTimes ?? []).map((d) => ({
    deptCode: d.deptCode,
    deptName: d.deptName,
    bedframeDays: d.bedframeDays,
    sofaDays: d.sofaDays,
  })),
);
emit(
  "schedule_entries",
  (M.scheduleEntries ?? []).map((s) => ({
    id: s.id,
    productionOrderId: opt(s.productionOrderId),
    soNumber: s.soNumber,
    productCode: s.productCode,
    category: s.category,
    customerDeliveryDate: s.customerDeliveryDate,
    customerName: s.customerName,
    hookkaExpectedDD: s.hookkaExpectedDD,
    deptSchedule: s.deptSchedule ?? [],
  })),
);

section("Price overrides + SO status changes");
emit(
  "price_overrides",
  (M.priceOverrides ?? []).map((p) => ({
    id: p.id,
    soId: p.soId,
    soNumber: p.soNumber,
    lineIndex: p.lineIndex,
    originalPrice: p.originalPrice,
    overridePrice: p.overridePrice,
    reason: p.reason,
    approvedBy: p.approvedBy,
    timestamp: p.timestamp,
  })),
);
emit(
  "so_status_changes",
  (M.soStatusChanges ?? []).map((s) => ({
    id: s.id,
    soId: s.soId,
    fromStatus: s.fromStatus,
    toStatus: s.toStatus,
    changedBy: s.changedBy,
    timestamp: s.timestamp,
    notes: s.notes,
    autoActions: s.autoActions ?? [],
  })),
);

section("BOM templates + BOM versions");
emit(
  "bom_templates",
  (M.bomTemplates ?? []).map((t) => ({
    id: t.id,
    productCode: t.productCode,
    baseModel: t.baseModel,
    category: t.category,
    l1Processes: t.l1Processes ?? [],
    wipComponents: t.wipComponents ?? [],
    version: t.version,
    versionStatus: t.versionStatus,
    effectiveFrom: t.effectiveFrom,
    effectiveTo: opt(t.effectiveTo),
    changeLog: opt(t.changeLog),
  })),
);
emit(
  "bom_versions",
  (M.bomVersions ?? []).map((v) => ({
    id: v.id,
    productId: v.productId,
    productCode: v.productCode,
    version: v.version,
    status: v.status,
    effectiveFrom: v.effectiveFrom,
    effectiveTo: opt(v.effectiveTo),
    tree: v.tree,
    totalMinutes: v.totalMinutes,
    labourCost: v.labourCost,
    materialCost: v.materialCost,
    totalCost: v.totalCost,
  })),
);

section("Production lead times (flat K/V)");
{
  const rows: Record<string, unknown>[] = [];
  const plt = M.productionLeadTimes;
  if (plt) {
    for (const [cat, map] of Object.entries(plt)) {
      for (const [dept, days] of Object.entries(map as Record<string, number>)) {
        rows.push({ category: cat, deptCode: dept, days });
      }
    }
  }
  emit("production_lead_times", rows);
}

// =============================================================================
// Footer
// =============================================================================

write("");
write("COMMIT;");
write("");
write(`-- Total inserted rows: ${totalRows}`);

// ---- Write file ------------------------------------------------------------

const outPath = path.resolve(process.cwd(), "migrations", "seed.sql");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out.join("\n"), "utf8");

console.log("");
console.log(`Wrote ${totalRows} total rows across ${out.filter((l) => l.startsWith("INSERT")).length} INSERTs.`);
console.log(`Output: ${outPath}`);
